version: '3'
services:


  ssb-deno-a:

    image: reto/deno-dev
    
    ports:
      - "127.0.0.1:18991:8990"

    volumes:
      - ../..:/monorepo:cached
      - ./container-data/ssb-deno-a/:/home/deno/.ssb

    environment:
      HOSTNAME: ssb-deno-a

    hostname: ssb-deno-a

    extra_hosts:
      - "host.docker.internal:host-gateway"

    command: /bin/sh -c "while sleep 1000; do :; done"

  ssb-deno-b:

    image: reto/deno-dev
    
    hostname: ssb-deno-b

    volumes:
      - ..:/workspace:cached
      - ./container-data/ssb-deno-b/:/home/deno/.ssb

    command: deno run -A --unstable /workspace/main.ts ; /bin/sh -c "while sleep 1000; do :; done"

  oasis-a:

    image: reto/oasis
    
    ports:
      - 3001:3000

    volumes:
      - ./container-data/oasis-a/:/home/node/.ssb

  oasis-b:

    image: reto/oasis
    
    ports:
      - 3002:3000

    volumes:
      - ./container-data/oasis-b:/home/node/.ssb
 
