version: '3'
services:
  tricerascuttler1:
    image: reto/tricerascuttler
    build: 
      context: ..
      dockerfile: tricerascuttler/Dockerfile
    ports:
      - "8989:8989"
    depends_on:
      - "virtuoso"
    environment:
#     - SPARQL_ENDPOINT_QUERY=http://anzograph:7070/sparql
#     - SPARQL_ENDPOINT_UPDATE=http://anzograph:7070/sparql
#     - SPARQL_ENDPOINT_QUERY=http://virtuoso:8890/sparql
#     - SPARQL_ENDPOINT_UPDATE=http://virtuoso:8890/sparql?default-graph-uri=urn:default
#      - SPARQL_ENDPOINT_QUERY=http://ld.plazi.org:8890/sparql
#      - SPARQL_ENDPOINT_UPDATE=http://ld.plazi.org:8890/sparql?default-graph-uri=urn:default
     - SPARQL_ENDPOINT_QUERY=http://blazegraph:8080/blazegraph/sparql
     - SPARQL_ENDPOINT_UPDATE=http://blazegraph:8080/blazegraph/sparql
     - SPARQL_ENDPOINT_CREDENTIALS=ssb:ssb
     - LOG_LEVEL=DEBUG
    volumes:
      - ./ssb-base:/home/deno/.ssb
    command: deno run -A --unstable main.ts --web.control.hostname 0.0.0.0 --logLevel ${LOG_LEVEL:-INFO} --outgoing false

  tricerascuttler2:
    image: reto/tricerascuttler
    build: 
      context: ..
      dockerfile: tricerascuttler/Dockerfile
    ports:
      - "8008:8008"
      - "127.0.0.1:18990:8990"
    depends_on:
      - "blazegraph"
    environment:
#     - SPARQL_ENDPOINT_QUERY=http://anzograph:7070/sparql
#     - SPARQL_ENDPOINT_UPDATE=http://anzograph:7070/sparql
#     - SPARQL_ENDPOINT_QUERY=http://virtuoso:8890/sparql
#     - SPARQL_ENDPOINT_UPDATE=http://virtuoso:8890/sparql?default-graph-uri=urn:default
     - SPARQL_ENDPOINT_QUERY=http://blazegraph:8080/blazegraph/sparql
     - SPARQL_ENDPOINT_UPDATE=http://blazegraph:8080/blazegraph/sparql
     - SPARQL_ENDPOINT_CREDENTIALS=ssb:ssb
     - LOG_LEVEL=DEBUG
    volumes:
      - ./ssb-base:/home/deno/.ssb
    command: deno run -A --unstable main.ts --web.control.hostname 0.0.0.0 --logLevel ${LOG_LEVEL:-INFO}


  blazegraph:
    image: "metaphacts/blazegraph-basic"
    volumes:
     - ../blazegraph-data:/blazegraph-data
    mem_reservation: 16g
  anzograph:
    image: cambridgesemantics/anzograph
    volumes:
      - ../anzograph-data:/opt/anzograph/persistence
#    ports:
#        - 8889:8080
  virtuoso:
    image: openlink/virtuoso-opensource-7
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
      DBA_PASSWORD: dba
    ports:
        - 8890:8890
    volumes:
        - ../virtuoso-data:/data

